version: "3"
services:

  portainer:
    image: portainer/portainer-ee
    container_name: portainer
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=America/Toronto    
    volumes:
      - ${DOCKER_PATH}/portainer:/data
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 9443:9443
      - 8000:8000
    restart: unless-stopped

  cloudflare-tunnel:
    image: cloudflare/cloudflared:2023.5.0
    container_name: cloudflare-tunnel
    environment:
      - TUNNEL_TOKEN=${TUNNEL_TOKEN}
    command: tunnel --no-autoupdate run
    restart: unless-stopped

  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=America/Toronto
      - WATCHTOWER_CLEANUP=true # Remove old images after updating
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
  
  homepage:
    image: ghcr.io/benphelps/homepage:latest
    container_name: homepage
    environment:
      - TZ=America/Toronto
    volumes:
      - ${DOCKER_PATH}/homepage:/app/config
      - /var/run/docker.sock:/var/run/docker.sock # Container integrations
    ports:
      - 3005:3000
    restart: unless-stopped

  syncthing:
    image: lscr.io/linuxserver/syncthing:latest
    container_name: syncthing
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=America/Toronto
    volumes:
      - ${DOCKER_PATH}/syncthing:/config
      - ${NAS_PATH}/backups/syncthing:/data1
    ports:
      - 8384:8384
      - 22000:22000/tcp
      - 22000:22000/udp
      - 21027:21027/udp
    restart: unless-stopped

  uptime-kuma:
    image: louislam/uptime-kuma
    container_name: uptime-kuma
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=America/Toronto
    volumes:
      - ${DOCKER_PATH}/uptime-kuma:/app/data
    ports:
      - 3001:3001
    restart: unless-stopped

  gluetun:
    image: qmcgaw/gluetun
    container_name: gluetun
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    ports:
      # Gluetun ports
      - 8888:8888/tcp
      - 8388:8388/tcp
      - 8388:8388/udp
      - 8111:8000/tcp # Control server
      # Container ports
      - 8112:8112 # Deluge
      - 6881:6881 # Deluge
      - 6881:6881/udp # Deluge
      - 9696:9696 # Prowlarr
      - 7878:7878 # Radarr
      - 8989:8989 # Sonarr
    volumes:
      - ${DOCKER_PATH}/gluetun:/gluetun
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=America/Toronto
      - VPN_SERVICE_PROVIDER=${VPN_SERVICE_PROVIDER}
      - SERVER_REGIONS=${SERVER_REGIONS}
      - OPENVPN_USER=${OPENVPN_USER}
      - OPENVPN_PASSWORD=${OPENVPN_PASSWORD}
    restart: unless-stopped

  deluge:
    image: lscr.io/linuxserver/deluge:latest
    container_name: deluge
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=America/Toronto
      - DELUGE_LOGLEVEL=error #optional
    volumes:
      - ${DOCKER_PATH}/deluge:/config
      - ${NAS_PATH}/downloads:/downloads
    network_mode: "service:gluetun"
    restart: unless-stopped

  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    network_mode: host
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=America/Toronto
      - VERSION=docker
      - PLEX_CLAIM= #optional
    volumes:
      - ${DOCKER_PATH}/plex:/config
      # Media file volumes
      - ${NAS_PATH}/movies:/movies
      - ${NAS_PATH}/tv:/tv
      - ${NAS_PATH}/anime:/anime
      - ${NAS_PATH}/standup:/standup
      - ${NAS_PATH}/music:/music
      - ${NAS_PATH}/audiobooks:/audiobooks
    restart: unless-stopped

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=America/Toronto
    volumes:
      - ${DOCKER_PATH}/prowlarr:/config
    network_mode: "service:gluetun"
    restart: unless-stopped

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=America/Toronto
    volumes:
      - ${DOCKER_PATH}/radarr:/config
      - ${NAS_PATH}/movies:/movies
    network_mode: "service:gluetun"
    restart: unless-stopped

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=America/Toronto
    volumes:
      - ${DOCKER_PATH}/sonarr:/config
      - ${NAS_PATH}/tv:/tv
    network_mode: "service:gluetun"
    restart: unless-stopped

  overseerr:
    image: lscr.io/linuxserver/overseerr:latest
    container_name: overseerr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=America/Toronto
    volumes:
      - ${DOCKER_PATH}/overseerr:/config
    ports:
      - 5055:5055
    restart: unless-stopped

  speedtest-tracker:
    image: henrywhitaker3/speedtest-tracker
    container_name: speedtest-tracker 
    ports:
        - 8765:80
    volumes:
        - ${DOCKER_PATH}/speedtest-tracker:/config
    environment:
        - PGID=${PGID}
        - PUID=${PUID}
        - TZ=America/Toronto
        - OOKLA_EULA_GDPR=true
    logging:
        driver: "json-file"
        options:
            max-file: "10"
            max-size: "200k"
    restart: unless-stopped

  apache:
    image: httpd
    container_name: apache
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=America/Toronto
    ports:
    - 8080:80
    volumes:
    - ${HOME_PATH}/websites:/usr/local/apache2/htdocs
    restart: unless-stopped

  mariadb:
    image: mariadb
    container_name: mariadb
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=America/Toronto
      - MARIADB_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}
      - MARIADB_USER=${MARIADB_USER}
      - MARIADB_PASSWORD=${MARIADB_PASSWORD}
    volumes:
      - ${DOCKER_PATH}/mariadb:/var/lib/mysql
    restart: unless-stopped

  adminer:
    image: adminer
    container_name: adminer
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=America/Toronto
      - ADMINER_DEFAULT_SERVER=mysql
      - ADMINER_DESIGN=pepa-linha-dark
    ports:
      - 8282:8080
    restart: unless-stopped

  pingvin:
    image: stonith404/pingvin-share
    container_name: pingvin
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=America/Toronto
    ports:
      - 3010:3000
    volumes:
      - ${DOCKER_PATH}/pingvin/data:/opt/app/backend/data
      - ${DOCKER_PATH}/pingvin/images:/opt/app/frontend/public/img
    restart: unless-stopped

  vscode-server:
    image: lscr.io/linuxserver/code-server:latest
    container_name: vscode-server
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=America/Toronto
      - SUDO_PASSWORD=${VSCODE_SUDO_PASSWORD}
      - PASSWORD=${VSCODE_PASSWORD}
      - PROXY_DOMAIN=${VSCODE_PROXY_DOMAIN}
      - DEFAULT_WORKSPACE=${HOME_PATH}
    volumes:
      - ${DOCKER_PATH}/vscode-server:/config
      - ${DOCKER_PATH}:/home
    ports:
      - 8443:8443
    restart: unless-stopped

  it-tools:
    image: corentinth/it-tools
    container_name: it-tools
    tty: true
    stdin_open: true
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=America/Toronto
    volumes:
      - ${DOCKER_PATH}/it-tools:/config
    ports:
      - 8484:80
    restart: unless-stopped

  metube:
    image: ghcr.io/alexta69/metube
    container_name: metube
    ports:
      - 8081:8081
    volumes:
      - /path/to/downloads:/downloads # Add custom path for downloads
    restart: unless-stopped

  kavita:
    image: kizaing/kavita:latest
    container_name: kavita
    environment:
      - TZ=America/Toronto
    volumes:
      - ${NAS_PATH}/manga:/manga
      - ${NAS_PATH}/comics:/comics
      - ${DOCKER_PATH}/kavita:/kavita/config
    ports:
      - 5001:5000
    restart: unless-stopped
